name: ci-cd

on:
  workflow_dispatch:
    inputs:
      environments:
        description: Environment to deploy
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore 'MyConsoleApp/MyConsoleApp.csproj'

      - name: Build
        run: dotnet build 'MyConsoleApp/MyConsoleApp.csproj' --no-restore

      - name: Publish
        run: dotnet publish 'MyConsoleApp/MyConsoleApp.csproj' -c Release -o ${{ github.workspace }}/artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-artifacts
          path: ${{ github.workspace }}/artifacts
